# Generated by Django 3.2.5 on 2021-08-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=150, unique=True),
        ),
    ]
