# Generated by Django 3.2.5 on 2021-08-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
