# Generated by Django 3.2.5 on 2021-08-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210825_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=256)),
                ('product_title', models.CharField(max_length=256)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
