# Generated by Django 3.2.5 on 2021-08-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210826_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='shopbydepartment',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
