# Generated by Django 3.2.5 on 2021-08-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210826_0049'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='product_name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategory',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='shopbydepartment',
            order_with_respect_to='name',
        ),
    ]
