# Generated by Django 3.2.5 on 2021-08-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210826_0116'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='productcategory',
            order_with_respect_to=None,
        ),
    ]
